# Generated by Django 5.0.2 on 2024-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
