# Generated by Django 5.0.2 on 2024-02-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(),
        ),
    ]
